# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jonny\OneDrive\Documents\Food_Lover_Ultimate\add_food.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 584)
        MainWindow.setMinimumSize(QtCore.QSize(622, 584))
        MainWindow.setMaximumSize(QtCore.QSize(622, 584))
        MainWindow.setStyleSheet("background-color: white;\n"
"color: black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 50, 561, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.kword = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.kword.setObjectName("kword")
        self.gridLayout.addWidget(self.kword, 2, 2, 1, 1)
        self.add_kword = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.add_kword.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 10px solid orange;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.add_kword.setObjectName("add_kword")
        self.gridLayout.addWidget(self.add_kword, 2, 3, 1, 1)
        self.description = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.description.setObjectName("description")
        self.gridLayout.addWidget(self.description, 1, 2, 1, 2)
        self.food_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.food_name.setAlignment(QtCore.Qt.AlignCenter)
        self.food_name.setObjectName("food_name")
        self.gridLayout.addWidget(self.food_name, 0, 2, 1, 2)
        self.add_food = QtWidgets.QPushButton(self.centralwidget)
        self.add_food.setGeometry(QtCore.QRect(230, 480, 191, 71))
        self.add_food.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 20px solid orange;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.add_food.setObjectName("add_food")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Keywords"))
        self.label_2.setText(_translate("MainWindow", "Description"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.add_kword.setText(_translate("MainWindow", "Add"))
        self.food_name.setPlaceholderText(_translate("MainWindow", "Food Name"))
        self.add_food.setText(_translate("MainWindow", "Add Food"))
