# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jonny\OneDrive\Documents\Food_Lover_Ultimate\chef.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("color: black;\n"
"background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 80, 611, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: orange;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.menu_table = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.menu_table.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: orange;\n"
"    color: white;\n"
"}")
        self.menu_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.menu_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.menu_table.setAutoScroll(False)
        self.menu_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.menu_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.menu_table.setObjectName("menu_table")
        self.menu_table.setColumnCount(5)
        self.menu_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.menu_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.menu_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.menu_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.menu_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.menu_table.setHorizontalHeaderItem(4, item)
        self.menu_table.horizontalHeader().setStretchLastSection(True)
        self.menu_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.menu_table)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(630, 80, 160, 461))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.id_num = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id_num.setFont(font)
        self.id_num.setStyleSheet("border: 2px solid orange; border-radius: 10px;\n"
"background-color:white;")
        self.id_num.setAlignment(QtCore.Qt.AlignCenter)
        self.id_num.setObjectName("id_num")
        self.verticalLayout_4.addWidget(self.id_num)
        self.error_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.error_label.setStyleSheet("color:rgb(162, 0, 0)")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.verticalLayout_4.addWidget(self.error_label)
        self.remove_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.remove_btn.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 10px solid orange;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.remove_btn.setObjectName("remove_btn")
        self.verticalLayout_4.addWidget(self.remove_btn)
        self.add_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.add_btn.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 10px solid orange;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout_4.addWidget(self.add_btn)
        self.file_complain = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.file_complain.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 10px solid orange;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.file_complain.setObjectName("file_complain")
        self.verticalLayout_4.addWidget(self.file_complain)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.refresh = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.refresh.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 10px solid orange;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.refresh.setObjectName("refresh")
        self.verticalLayout_4.addWidget(self.refresh)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Menu"))
        item = self.menu_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.menu_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ratings"))
        item = self.menu_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Num Ratings"))
        item = self.menu_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Chef ID"))
        item = self.menu_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description"))
        self.id_num.setPlaceholderText(_translate("MainWindow", "Enter Worker ID"))
        self.remove_btn.setText(_translate("MainWindow", "Remove Item"))
        self.add_btn.setText(_translate("MainWindow", "Add Food"))
        self.file_complain.setText(_translate("MainWindow", "File Importer Complain"))
        self.refresh.setText(_translate("MainWindow", "Refresh"))
