# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jonny\OneDrive\Documents\Food_Lover_Ultimate\chef_to_importer_complaint.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(332, 442)
        MainWindow.setStyleSheet("background-color: white;\n"
"color: black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 311, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.quality = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.quality.setObjectName("quality")
        self.gridLayout.addWidget(self.quality, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: orange;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.fraud = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.fraud.setObjectName("fraud")
        self.gridLayout.addWidget(self.fraud, 3, 1, 1, 1)
        self.importer_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.importer_name.setAlignment(QtCore.Qt.AlignCenter)
        self.importer_name.setObjectName("importer_name")
        self.gridLayout.addWidget(self.importer_name, 1, 0, 1, 2)
        self.send_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.send_btn.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 20px solid orange;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.send_btn.setObjectName("send_btn")
        self.gridLayout.addWidget(self.send_btn, 5, 0, 1, 2)
        self.complaint_text = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.complaint_text.setObjectName("complaint_text")
        self.gridLayout.addWidget(self.complaint_text, 2, 0, 1, 2)
        self.err_msg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.err_msg.setStyleSheet("color: rgb(166, 0, 0);")
        self.err_msg.setText("")
        self.err_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.err_msg.setObjectName("err_msg")
        self.gridLayout.addWidget(self.err_msg, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.quality.setText(_translate("MainWindow", "Food Quality"))
        self.label.setText(_translate("MainWindow", "File Complaint"))
        self.fraud.setText(_translate("MainWindow", "Fraud"))
        self.importer_name.setPlaceholderText(_translate("MainWindow", "Importer Name"))
        self.send_btn.setText(_translate("MainWindow", "Send Complaint"))
