# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forum.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ratingNumber = QtWidgets.QPushButton(self.centralwidget)
        self.ratingNumber.setGeometry(QtCore.QRect(290, 130, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ratingNumber.setFont(font)
        self.ratingNumber.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    border: 2px solid orange;\n"
"    border-radius: 30px;\n"
"    color: orange;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: orange;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"}")
        self.ratingNumber.setObjectName("ratingNumber")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 80, 799, 40))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: orange;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 201, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.name.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(True)
        self.name.setFont(font)
        self.name.setStyleSheet("QLabel  {\n"
"    color: rgb(255, 170, 0);\n"
"}")
        self.name.setScaledContents(False)
        self.name.setObjectName("name")
        self.horizontalLayout_3.addWidget(self.name)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.ratingNumber_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ratingNumber_2.setGeometry(QtCore.QRect(220, 130, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ratingNumber_2.setFont(font)
        self.ratingNumber_2.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    border: 2px solid orange;\n"
"    border-radius: 30px;\n"
"    color: orange;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: orange;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"}")
        self.ratingNumber_2.setObjectName("ratingNumber_2")
        self.ratingNumber_3 = QtWidgets.QPushButton(self.centralwidget)
        self.ratingNumber_3.setGeometry(QtCore.QRect(430, 130, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ratingNumber_3.setFont(font)
        self.ratingNumber_3.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    border: 2px solid orange;\n"
"    border-radius: 30px;\n"
"    color: orange;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: orange;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"}")
        self.ratingNumber_3.setObjectName("ratingNumber_3")
        self.ratingNumber_4 = QtWidgets.QPushButton(self.centralwidget)
        self.ratingNumber_4.setGeometry(QtCore.QRect(360, 130, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ratingNumber_4.setFont(font)
        self.ratingNumber_4.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    border: 2px solid orange;\n"
"    border-radius: 30px;\n"
"    color: orange;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: orange;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"}")
        self.ratingNumber_4.setObjectName("ratingNumber_4")
        self.ratingNumber_5 = QtWidgets.QPushButton(self.centralwidget)
        self.ratingNumber_5.setGeometry(QtCore.QRect(500, 130, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ratingNumber_5.setFont(font)
        self.ratingNumber_5.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    border: 2px solid orange;\n"
"    border-radius: 30px;\n"
"    color: orange;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: orange;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButtonClick {\n"
"    background-color: orange;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"}")
        self.ratingNumber_5.setObjectName("ratingNumber_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ratingNumber.setText(_translate("MainWindow", "2"))
        self.label_7.setText(_translate("MainWindow", "How did you like your"))
        self.label_6.setText(_translate("MainWindow", "foodName"))
        self.label_8.setText(_translate("MainWindow", "?"))
        self.label.setText(_translate("MainWindow", "Hey,"))
        self.name.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "!"))
        self.ratingNumber_2.setText(_translate("MainWindow", "1"))
        self.ratingNumber_3.setText(_translate("MainWindow", "4"))
        self.ratingNumber_4.setText(_translate("MainWindow", "3"))
        self.ratingNumber_5.setText(_translate("MainWindow", "5"))
