# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jonny\OneDrive\Documents\Food_Lover_Ultimate\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 12, 801, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\jonny\\OneDrive\\Documents\\Food_Lover_Ultimate\\Images/food_lover.ico"))
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: orange;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(270, 250, 261, 96))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_email_entry = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.main_email_entry.setStyleSheet("border: 2px solid orange; border-radius: 10px;")
        self.main_email_entry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.main_email_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.main_email_entry.setObjectName("main_email_entry")
        self.verticalLayout_3.addWidget(self.main_email_entry)
        self.main_pw_entry = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.main_pw_entry.setStyleSheet("border: 2px solid orange; border-radius: 10px")
        self.main_pw_entry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.main_pw_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.main_pw_entry.setObjectName("main_pw_entry")
        self.verticalLayout_3.addWidget(self.main_pw_entry)
        self.login_error = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.login_error.setStyleSheet("color: rgb(255, 96, 96);")
        self.login_error.setText("")
        self.login_error.setAlignment(QtCore.Qt.AlignCenter)
        self.login_error.setObjectName("login_error")
        self.verticalLayout_3.addWidget(self.login_error)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(320, 330, 171, 110))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.register_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.register_btn.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 2px solid orange;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.register_btn.setObjectName("register_btn")
        self.gridLayout.addWidget(self.register_btn, 1, 1, 1, 1)
        self.login_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.login_btn.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 2px solid orange;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.login_btn.setObjectName("login_btn")
        self.gridLayout.addWidget(self.login_btn, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("color: black;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.surf_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.surf_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\jonny\\OneDrive\\Documents\\Food_Lover_Ultimate\\Images/surf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.surf_btn.setIcon(icon)
        self.surf_btn.setIconSize(QtCore.QSize(50, 50))
        self.surf_btn.setObjectName("surf_btn")
        self.gridLayout.addWidget(self.surf_btn, 2, 0, 1, 2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 549, 801, 21))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setStyleSheet("color: orange;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 801, 16))
        self.stackedWidget.setObjectName("stackedWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Welcome to"))
        self.label_6.setText(_translate("MainWindow", "Food Lover"))
        self.main_email_entry.setPlaceholderText(_translate("MainWindow", "Email"))
        self.main_pw_entry.setPlaceholderText(_translate("MainWindow", "Password"))
        self.register_btn.setText(_translate("MainWindow", "Register"))
        self.login_btn.setText(_translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "Not registered ?"))
        self.label_4.setText(_translate("MainWindow", "Copyright: Group F"))
