# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jonny\OneDrive\Documents\Food_Lover_Ultimate\manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("color: black;\n"
"background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 550, 801, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setStyleSheet("color: black;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 551))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border: 1px solid lightgray;\n"
"  top:-1px; \n"
"  background: rgb(245, 245, 245);; \n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  background: rgb(239, 159, 0); \n"
"color:white;\n"
"  border: 1px solid rgb(239, 159, 0); \n"
"  padding: 15px;\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"  background: rgb(172, 115, 0); \n"
"  margin-bottom: -1px; \n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Home.setAutoFillBackground(False)
        self.Home.setStyleSheet("")
        self.Home.setObjectName("Home")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Home)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 100, 251, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcome_manager_txt = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.welcome_manager_txt.setFont(font)
        self.welcome_manager_txt.setTextFormat(QtCore.Qt.PlainText)
        self.welcome_manager_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_manager_txt.setObjectName("welcome_manager_txt")
        self.verticalLayout.addWidget(self.welcome_manager_txt)
        self.tabWidget.addTab(self.Home, "")
        self.worker_tab = QtWidgets.QWidget()
        self.worker_tab.setObjectName("worker_tab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.worker_tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(610, 20, 160, 451))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.id_num = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id_num.setFont(font)
        self.id_num.setStyleSheet("border: 2px solid orange; border-radius: 10px;\n"
"background-color:white;")
        self.id_num.setAlignment(QtCore.Qt.AlignCenter)
        self.id_num.setObjectName("id_num")
        self.verticalLayout_4.addWidget(self.id_num)
        self.error_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.error_label.setStyleSheet("color:rgb(162, 0, 0)")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.verticalLayout_4.addWidget(self.error_label)
        self.change_wage = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.change_wage.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 10px solid orange;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.change_wage.setObjectName("change_wage")
        self.verticalLayout_4.addWidget(self.change_wage)
        self.fire_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.fire_btn.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 10px solid orange;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.fire_btn.setObjectName("fire_btn")
        self.verticalLayout_4.addWidget(self.fire_btn)
        self.refresh = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.refresh.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 10px solid orange;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.refresh.setObjectName("refresh")
        self.verticalLayout_4.addWidget(self.refresh)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.hire_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.hire_btn.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 20px solid orange;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.hire_btn.setObjectName("hire_btn")
        self.verticalLayout_4.addWidget(self.hire_btn)
        self.worker_table = QtWidgets.QTableWidget(self.worker_tab)
        self.worker_table.setGeometry(QtCore.QRect(0, 10, 591, 481))
        font = QtGui.QFont()
        font.setKerning(True)
        self.worker_table.setFont(font)
        self.worker_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.worker_table.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: orange;\n"
"    color: white;\n"
"}")
        self.worker_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.worker_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.worker_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.worker_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.worker_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.worker_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.worker_table.setObjectName("worker_table")
        self.worker_table.setColumnCount(5)
        self.worker_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.worker_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.worker_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.worker_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.worker_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.worker_table.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.worker_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Copyright: Team F"))
        self.welcome_manager_txt.setText(_translate("MainWindow", "Welcome Manager !"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Home), _translate("MainWindow", "Home"))
        self.id_num.setPlaceholderText(_translate("MainWindow", "Enter Worker ID"))
        self.change_wage.setText(_translate("MainWindow", "Change Wages"))
        self.fire_btn.setText(_translate("MainWindow", "Fire Employee"))
        self.refresh.setText(_translate("MainWindow", "Refresh"))
        self.hire_btn.setText(_translate("MainWindow", "Hire Employee"))
        item = self.worker_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Position"))
        item = self.worker_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.worker_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ID"))
        item = self.worker_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Wage"))
        item = self.worker_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Rating"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.worker_tab), _translate("MainWindow", "Workers"))
