# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jonny\OneDrive\Documents\Food_Lover_Ultimate\manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("color: black;\n"
"background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 550, 801, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setStyleSheet("color: black;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 551))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border: 1px solid lightgray;\n"
"  top:-1px; \n"
"  background: rgb(245, 245, 245);; \n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  background: black; \n"
"color:white;\n"
"  border: 1px solid black; \n"
"  padding: 15px;\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"  background: rgb(79, 79, 79); \n"
"  margin-bottom: -1px; \n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Home.setAutoFillBackground(False)
        self.Home.setStyleSheet("")
        self.Home.setObjectName("Home")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Home)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 100, 251, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcome_manager_txt = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.welcome_manager_txt.setFont(font)
        self.welcome_manager_txt.setTextFormat(QtCore.Qt.PlainText)
        self.welcome_manager_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_manager_txt.setObjectName("welcome_manager_txt")
        self.verticalLayout.addWidget(self.welcome_manager_txt)
        self.tabWidget.addTab(self.Home, "")
        self.worker_tab = QtWidgets.QWidget()
        self.worker_tab.setObjectName("worker_tab")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.worker_tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(180, 80, 411, 301))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.view_complaints_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.view_complaints_btn.setFont(font)
        self.view_complaints_btn.setStyleSheet("background-color: black;\n"
"color: white;\n"
"border: 25px solid;")
        self.view_complaints_btn.setObjectName("view_complaints_btn")
        self.verticalLayout_3.addWidget(self.view_complaints_btn)
        self.hire_workers_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hire_workers_btn.setFont(font)
        self.hire_workers_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hire_workers_btn.setStyleSheet("background-color: black;\n"
"color: white;\n"
"border: 25px solid;")
        self.hire_workers_btn.setObjectName("hire_workers_btn")
        self.verticalLayout_3.addWidget(self.hire_workers_btn)
        self.wages_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wages_btn.setFont(font)
        self.wages_btn.setStyleSheet("background-color: black;\n"
"color: white;\n"
"border: 25px solid;")
        self.wages_btn.setObjectName("wages_btn")
        self.verticalLayout_3.addWidget(self.wages_btn)
        self.tabWidget.addTab(self.worker_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Copyright: Team F"))
        self.welcome_manager_txt.setText(_translate("MainWindow", "Welcome Manager !"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Home), _translate("MainWindow", "Home"))
        self.view_complaints_btn.setText(_translate("MainWindow", "View Complaints"))
        self.hire_workers_btn.setText(_translate("MainWindow", "Hire/Fire Workers"))
        self.wages_btn.setText(_translate("MainWindow", "Wages"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.worker_tab), _translate("MainWindow", "Workers"))
