# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jonny\OneDrive\Documents\Food_Lover_Ultimate\promote.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(191, 224)
        MainWindow.setMinimumSize(QtCore.QSize(191, 224))
        MainWindow.setMaximumSize(QtCore.QSize(191, 224))
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 171, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.reg = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.reg.setFont(font)
        self.reg.setStyleSheet("color:orange;")
        self.reg.setObjectName("reg")
        self.gridLayout.addWidget(self.reg, 4, 0, 1, 1)
        self.vip = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vip.setFont(font)
        self.vip.setStyleSheet("color: orange;")
        self.vip.setObjectName("vip")
        self.gridLayout.addWidget(self.vip, 4, 1, 1, 1)
        self.na = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.na.setFont(font)
        self.na.setStyleSheet("color: orange;")
        self.na.setObjectName("na")
        self.gridLayout.addWidget(self.na, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: orange")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.email = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.email.setStyleSheet("border: 2px solid orange; border-radius: 10px;\n"
"background-color:white;")
        self.email.setAlignment(QtCore.Qt.AlignCenter)
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 2, 0, 1, 3)
        self.err_msg = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.err_msg.setStyleSheet("color: rgb(173, 0, 0);")
        self.err_msg.setText("")
        self.err_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.err_msg.setObjectName("err_msg")
        self.gridLayout.addWidget(self.err_msg, 3, 0, 1, 3)
        self.promo_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.promo_btn.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 10px solid orange;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.promo_btn.setObjectName("promo_btn")
        self.gridLayout.addWidget(self.promo_btn, 5, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reg.setText(_translate("MainWindow", "Regular"))
        self.vip.setText(_translate("MainWindow", "VIP"))
        self.na.setText(_translate("MainWindow", "N/A"))
        self.label.setText(_translate("MainWindow", "Enter Users Email"))
        self.email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.promo_btn.setText(_translate("MainWindow", "Promote"))
