# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './register_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("color: black;\n"
"background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 801, 239))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap(".\\Images/food_lover.ico"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: orange;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 290, 214, 144))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name_reg = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.name_reg.setStyleSheet("border: 2px solid orange; border-radius: 10px;")
        self.name_reg.setAlignment(QtCore.Qt.AlignCenter)
        self.name_reg.setObjectName("name_reg")
        self.verticalLayout_2.addWidget(self.name_reg)
        self.email_reg = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.email_reg.setStyleSheet("border: 2px solid orange; border-radius: 10px;")
        self.email_reg.setText("")
        self.email_reg.setAlignment(QtCore.Qt.AlignCenter)
        self.email_reg.setObjectName("email_reg")
        self.verticalLayout_2.addWidget(self.email_reg)
        self.pw_reg = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pw_reg.setStyleSheet("border: 2px solid orange; border-radius: 10px;")
        self.pw_reg.setAlignment(QtCore.Qt.AlignCenter)
        self.pw_reg.setObjectName("pw_reg")
        self.verticalLayout_2.addWidget(self.pw_reg)
        self.acc_type = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        self.acc_type.setFont(font)
        self.acc_type.setStyleSheet("color: black;\n"
"background-color: white; border: 2px solid ")
        self.acc_type.setEditable(False)
        self.acc_type.setCurrentText("")
        self.acc_type.setObjectName("acc_type")
        self.acc_type.addItem("")
        self.acc_type.addItem("")
        self.acc_type.addItem("")
        self.verticalLayout_2.addWidget(self.acc_type)
        self.reg_error = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.reg_error.setFont(font)
        self.reg_error.setStyleSheet("color: rgb(255, 96, 96);")
        self.reg_error.setText("")
        self.reg_error.setAlignment(QtCore.Qt.AlignCenter)
        self.reg_error.setObjectName("reg_error")
        self.verticalLayout_2.addWidget(self.reg_error)
        self.reg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reg_btn.setGeometry(QtCore.QRect(360, 450, 101, 31))
        self.reg_btn.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 2px solid orange;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.reg_btn.setObjectName("reg_btn")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(0, 0, 51, 51))
        self.back_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Images/arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon)
        self.back_btn.setIconSize(QtCore.QSize(50, 50))
        self.back_btn.setObjectName("back_btn")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 570, 801, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Sign Up, It\'s"))
        self.label_6.setText(_translate("MainWindow", "Free"))
        self.name_reg.setPlaceholderText(_translate("MainWindow", "Name"))
        self.email_reg.setPlaceholderText(_translate("MainWindow", "Email"))
        self.pw_reg.setPlaceholderText(_translate("MainWindow", "Password"))
        self.acc_type.setPlaceholderText(_translate("MainWindow", "Account Type"))
        self.acc_type.setItemText(0, _translate("MainWindow", "Customer Account"))
        self.acc_type.setItemText(1, _translate("MainWindow", "Store Account"))
        self.acc_type.setItemText(2, _translate("MainWindow", "Surfer Account"))
        self.reg_btn.setText(_translate("MainWindow", "Register"))
        self.label_4.setText(_translate("MainWindow", "Copyright: Team F"))
