# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jonny\OneDrive\Documents\Food_Lover_Ultimate\search_browse.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(710, 10, 81, 91))
        self.image.setStyleSheet("")
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("c:\\Users\\jonny\\OneDrive\\Documents\\Food_Lover_Ultimate\\food_lover.png"))
        self.image.setScaledContents(True)
        self.image.setWordWrap(False)
        self.image.setObjectName("image")
        self.textInput = QtWidgets.QTextEdit(self.centralwidget)
        self.textInput.setGeometry(QtCore.QRect(340, 120, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setItalic(True)
        self.textInput.setFont(font)
        self.textInput.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid orange;\n"
"    background-color: transparent;\n"
"}")
        self.textInput.setObjectName("textInput")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(620, 120, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.searchButton.setFont(font)
        self.searchButton.setStyleSheet("QPushButton {\n"
"    color: orange;\n"
"    background: transparent;\n"
"    border: 2px solid orange;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    color: white;\n"
"    background: orange;\n"
"    border: 2px solid orange;\n"
"    border-radius: 16px;\n"
"}")
        self.searchButton.setObjectName("searchButton")
        self.columnView = QtWidgets.QColumnView(self.centralwidget)
        self.columnView.setGeometry(QtCore.QRect(10, 180, 781, 371))
        self.columnView.setStyleSheet("QColumnView {\n"
"    background-color: transparent;\n"
"    border-radius: 16px;\n"
"    border: 2px solid orange;\n"
"}")
        self.columnView.setObjectName("columnView")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 60, 49, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 211, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.name.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(True)
        self.name.setFont(font)
        self.name.setStyleSheet("QLabel  {\n"
"    color: rgb(255, 170, 0);\n"
"}")
        self.name.setScaledContents(False)
        self.name.setObjectName("name")
        self.horizontalLayout_2.addWidget(self.name)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(90, 110, 246, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_5.setFont(font)
        self.label_5.setMouseTracking(False)
        self.label_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgb(255, 170, 0)\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Hello,"))
        self.name.setText(_translate("MainWindow", "Name"))
        self.label_5.setText(_translate("MainWindow", "It\'s time to"))
        self.label_3.setText(_translate("MainWindow", "eat!"))
