# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jonny\OneDrive\Documents\Food_Lover_Ultimate\voting.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 80, 799, 40))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.ratingGreeting = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.ratingGreeting.setContentsMargins(0, 0, 0, 0)
        self.ratingGreeting.setObjectName("ratingGreeting")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ratingGreeting.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.ratingGreeting.addWidget(self.label_7)
        self.foodName = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.foodName.setFont(font)
        self.foodName.setStyleSheet("QLabel {\n"
"    color: orange;\n"
"}")
        self.foodName.setAlignment(QtCore.Qt.AlignCenter)
        self.foodName.setObjectName("foodName")
        self.ratingGreeting.addWidget(self.foodName)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.ratingGreeting.addWidget(self.label_8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ratingGreeting.addItem(spacerItem1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 201, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.greeting = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.greeting.setContentsMargins(0, 0, 0, 0)
        self.greeting.setObjectName("greeting")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.greeting.addWidget(self.label)
        self.name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.name.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setUnderline(True)
        self.name.setFont(font)
        self.name.setStyleSheet("QLabel  {\n"
"    color: rgb(255, 170, 0);\n"
"}")
        self.name.setScaledContents(False)
        self.name.setObjectName("name")
        self.greeting.addWidget(self.name)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.greeting.addWidget(self.label_2)
        self.ratingGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.ratingGroup.setGeometry(QtCore.QRect(180, 130, 431, 71))
        self.ratingGroup.setTitle("")
        self.ratingGroup.setObjectName("ratingGroup")
        self.ratingNumber_2 = QtWidgets.QPushButton(self.ratingGroup)
        self.ratingNumber_2.setGeometry(QtCore.QRect(50, 0, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ratingNumber_2.setFont(font)
        self.ratingNumber_2.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    border: 2px solid orange;\n"
"    border-radius: 30px;\n"
"    color: orange;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: orange;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"}")
        self.ratingNumber_2.setObjectName("ratingNumber_2")
        self.ratingNumber_4 = QtWidgets.QPushButton(self.ratingGroup)
        self.ratingNumber_4.setGeometry(QtCore.QRect(190, 0, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ratingNumber_4.setFont(font)
        self.ratingNumber_4.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    border: 2px solid orange;\n"
"    border-radius: 30px;\n"
"    color: orange;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: orange;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"}")
        self.ratingNumber_4.setObjectName("ratingNumber_4")
        self.ratingNumber = QtWidgets.QPushButton(self.ratingGroup)
        self.ratingNumber.setGeometry(QtCore.QRect(120, 0, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ratingNumber.setFont(font)
        self.ratingNumber.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    border: 2px solid orange;\n"
"    border-radius: 30px;\n"
"    color: orange;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: orange;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"}")
        self.ratingNumber.setObjectName("ratingNumber")
        self.ratingNumber_5 = QtWidgets.QPushButton(self.ratingGroup)
        self.ratingNumber_5.setGeometry(QtCore.QRect(330, 0, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ratingNumber_5.setFont(font)
        self.ratingNumber_5.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    border: 2px solid orange;\n"
"    border-radius: 30px;\n"
"    color: orange;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: orange;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButtonClick {\n"
"    background-color: orange;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"}")
        self.ratingNumber_5.setObjectName("ratingNumber_5")
        self.ratingNumber_3 = QtWidgets.QPushButton(self.ratingGroup)
        self.ratingNumber_3.setGeometry(QtCore.QRect(260, 0, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ratingNumber_3.setFont(font)
        self.ratingNumber_3.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    border: 2px solid orange;\n"
"    border-radius: 30px;\n"
"    color: orange;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: orange;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"}")
        self.ratingNumber_3.setObjectName("ratingNumber_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 200, 781, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.ratingResponse = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.ratingResponse.setFont(font)
        self.ratingResponse.setStyleSheet("QLabel {\n"
"    color: orange;\n"
"}")
        self.ratingResponse.setAlignment(QtCore.Qt.AlignCenter)
        self.ratingResponse.setObjectName("ratingResponse")
        self.horizontalLayout_5.addWidget(self.ratingResponse)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.ratingMessage = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.ratingMessage.setStyleSheet("border: 3px solid orange; border-radius: 10px; background: transparent;")
        self.ratingMessage.setObjectName("ratingMessage")
        self.verticalLayout.addWidget(self.ratingMessage)
        self.submitMessage = QtWidgets.QPushButton(self.centralwidget)
        self.submitMessage.setGeometry(QtCore.QRect(10, 390, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.submitMessage.setFont(font)
        self.submitMessage.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border: 2px solid orange;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButtonHover {\n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.submitMessage.setObjectName("submitMessage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "How did you like your"))
        self.foodName.setText(_translate("MainWindow", "foodName"))
        self.label_8.setText(_translate("MainWindow", "?"))
        self.label.setText(_translate("MainWindow", "Hey,"))
        self.name.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "!"))
        self.ratingNumber_2.setText(_translate("MainWindow", "1"))
        self.ratingNumber_4.setText(_translate("MainWindow", "3"))
        self.ratingNumber.setText(_translate("MainWindow", "2"))
        self.ratingNumber_5.setText(_translate("MainWindow", "5"))
        self.ratingNumber_3.setText(_translate("MainWindow", "4"))
        self.ratingResponse.setText(_translate("MainWindow", "ratingResponse"))
        self.submitMessage.setText(_translate("MainWindow", "Submit"))
